"""Full SCAIL2Model forward parity at a tiny i2v config, fp32, CPU oracle.

Weights are generated by upstream init, copied into MLX via the production
key-remap (utils/weights.py), so this also locks the state-dict mapping.
"""
import numpy as np
import pytest
import torch

import mlx.core as mx

from scail2_mlx.modules.model_scail2 import SCAIL2Model
from scail2_mlx.utils.weights import load_state_dict_np

from ._helpers import assert_parity, make_seeded_input

TINY = dict(
    model_type="i2v",
    patch_size=(1, 2, 2),
    text_len=512,  # T5_CONTEXT_TOKEN_NUMBER is hardcoded upstream
    in_dim=20,  # 16 latent + 4 i2v mask channels appended in forward
    mask_dim=28,
    dim=64,
    ffn_dim=128,
    freq_dim=32,
    text_dim=48,
    out_dim=16,
    num_heads=4,  # head_dim 16 -> c=8, rope split [4, 2, 2]
    num_layers=2,
    qk_norm=True,
    cross_attn_norm=True,
)

T_, H_, W_ = 2, 8, 8  # latent frames / latent spatial (rope grid 4x4, pose 2x2)


def _make_inputs(history: bool):
    g = lambda shape, seed: make_seeded_input(shape, seed=seed)
    inputs = dict(
        x=[g((16, T_, H_, W_), 1)],
        ref_latents=[g((16, 1, H_, W_), 2)],
        ref_masks=[g((28, 1 + T_, H_, W_), 3)],
        pose_latents=[g((16, T_, H_ // 2, W_ // 2), 4)],
        driving_masks=[g((28, T_, H_ // 2, W_ // 2), 5)],
        clip_fea=g((1, 257, 1280), 6),
        context=[g((7, TINY["text_dim"]), 8)],
        t=np.array([500.0], dtype=np.float32),
    )
    if history:
        inputs["history_mask"] = [g((4, T_, H_, W_), 9)]
    return inputs


@pytest.mark.parametrize("replace_flag", [False, True])
@pytest.mark.parametrize("history", [False, True])
def test_forward_parity(pt_scail2, replace_flag, history):
    torch.manual_seed(0)
    pt_model = pt_scail2.SCAIL2Model(**TINY).eval().float()
    state = {k: v.detach().numpy() for k, v in pt_model.state_dict().items()}

    mx_model = SCAIL2Model(**TINY)
    load_state_dict_np(mx_model, state, strict=True)

    inp = _make_inputs(history)

    with torch.no_grad():
        pt_out = pt_model(
            x=[torch.from_numpy(v) for v in inp["x"]],
            pose_latents=[torch.from_numpy(v) for v in inp["pose_latents"]],
            driving_masks=[torch.from_numpy(v) for v in inp["driving_masks"]],
            ref_latents=[torch.from_numpy(v) for v in inp["ref_latents"]],
            ref_masks=[torch.from_numpy(v) for v in inp["ref_masks"]],
            t=torch.from_numpy(inp["t"]),
            context=[torch.from_numpy(v) for v in inp["context"]],
            seq_len=int(1e10),
            replace_flag=replace_flag,
            history_mask=(
                [torch.from_numpy(v) for v in inp["history_mask"]] if history else None
            ),
            clip_fea=torch.from_numpy(inp["clip_fea"]),
        )

    mx_out = mx_model(
        x=[mx.array(v) for v in inp["x"]],
        pose_latents=[mx.array(v) for v in inp["pose_latents"]],
        driving_masks=[mx.array(v) for v in inp["driving_masks"]],
        ref_latents=[mx.array(v) for v in inp["ref_latents"]],
        ref_masks=[mx.array(v) for v in inp["ref_masks"]],
        t=mx.array(inp["t"]),
        context=[mx.array(v) for v in inp["context"]],
        seq_len=int(1e10),
        replace_flag=replace_flag,
        history_mask=([mx.array(v) for v in inp["history_mask"]] if history else None),
        clip_fea=mx.array(inp["clip_fea"]),
    )

    assert len(pt_out) == len(mx_out) == 1
    assert_parity(
        pt_out[0],
        mx_out[0],
        1e-3,
        name=f"SCAIL2Model fwd replace={replace_flag} history={history}",
    )
